### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by demlak** [koffienl/ESPimatic#1]
hi.. i just tried to compile this project in the arduino IDE..
setup:
- fresh 1.6.7 Arduino IDE
- added esp8266 board by using stable or staging version via boardmanager link like discribed in here: https://github.com/esp8266/Arduino
- added libraries through library manager that have "esp" in name or description
- downloaded your project as zip..
- extracted and installed all libraries 
- tried to start compiling

error message is very long.. starts and ends with:
'EepromMD5' was not declared in this scope

i can´t find infos about eeprommd5 and arduino on the web

**Comment by koffienl** [comment]
Can you post the entire compilation log on pastebin ?
The MD5 should be in the 2.0 boardmanager: Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266\MD5Builder.cpp

**Comment by demlak** [comment]
complete log:
http://pastebin.com/YqXXxEqB

MD5Builder.cpp is present in:
D:\projects\esp\arduino-1.6.7\portable\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266

as you can see.. im using the portable version of the arduino IDE on windows.. 
(to make it portable just put a folder named "portable" in the arduino-IDE folder)

the board im using is the nodeMCU v1.0

**Comment by koffienl** [comment]
It seems I can reproduce this error on Arduino 1.6.7 while it works without any problems on 1.6.5

**Comment by demlak** [comment]
yeah.. just installed 1.6.5.. it´s flashing right now.. thx anyway..

**Comment by koffienl** [comment]
Did you installed the Git version of es8266 core or used boardmanager on 1.6.7 ?

**Comment by demlak** [comment]
boardmanager

**Comment by koffienl** [comment]
Solution was to use Arduino IDE 1.6.5 with boardmanager 2.0.0
Closing this issue
