### ISSUE TITLE
Unable to compile due to base 64 encode error

### ISSUE THREAD

**Issue by taralshah123** [koffienl/ESPimatic#12]
C:\Users\Taral\Documents\Arduino\ESPimatic\ESPimatic.ino: In function 'void send_data(String, String)':

ESPimatic:2292: error: 'base64_encode' was not declared in this scope

   base64_encode(unameenc, uname, strlen(uname));

```
                                           ^
```

C:\Users\Taral\Documents\Arduino\ESPimatic\ESPimatic.ino: In function 'String get_data(String)':

ESPimatic:2341: error: 'base64_encode' was not declared in this scope

   base64_encode(unameenc, uname, strlen(uname));

```
                                           ^
```

**Comment by incmve** [comment]
make sure you have Arduino IDE 1.6.5 with ESP8266 boardmanager 2.0.0

**Comment by taralshah123** [comment]
complies perfectly as you suggested. Thanks for your instant response.

**Comment by knophoane** [comment]
Good afternoon,

I have not been able to upload my ESPimatic to the ESP8266-12E, and now I get messages every time I can not find the LedcontrolSPIESp8266.h file when I try to upload or to Verify / Compile. I get the following error message:

ESPimatic.ino: 5: 34: fatal error: LedControlSPIESP8266.h: No such file or directory
compilation terminated.
Error compiling.

Can you or someone else tell me what to do?

Sincerely,

Dennis

Goedemiddag,

Ik kan sinds kort mijn ESPimatic niet meer uploaden naar de ESP8266-12E, ik krijg nu elke keer meldingen dat hij de LedcontrolSPIESp8266.h bestand niet kan vinden als ik probeer te uploaden of te Verify/Compile. ik krijg onderstaande fout melding:

ESPimatic.ino:5:34: fatal error: LedControlSPIESP8266.h: No such file or directory
compilation terminated.
Fout bij compileren.

kan jij of iemand anders mij vertellen wat ik moet doen?

Met vriendelijke groet,

Dennis

**Comment by S-Knop** [comment]
LedControlSPIESP8266.h should be in directory :
ESPimatic-master\libraries\LedControlSpipESP8266\LedControlSPIESP8266.h 
if that is not the case paste it there and restart arduino ide.

Kan je controlleren of LedControlSPIESP8266.h  in de map libraries staat van espimatic.
ESPimatic-master\libraries\LedControlSpipESP8266\LedControlSPIESP8266.h.
als die ontbreekt kopieer de map LedControlSpipESP8266 naar de map libraries en start Arduino IDE opnieuw op.

**Comment by knophoane** [comment]
Ja het bestand staat in het volgende pad:

C:\Users\Dennis\Documents\Raspberry PI\ESPimatic-master\libraries\LedControlSpipESP8266

maar krijg nog steeds de volgende foutmelding:

ESPimatic.ino:5:34: fatal error: LedControlSPIESP8266.h: No such file or directory
compilation terminated.
Fout bij compileren.

Heb het ook op een ander systeem geprobeerd, maar zelfde resultaat.

**Comment by S-Knop** [comment]
bij mij staan de libraries ook in C:\Users%username%\Documents\Arduino\libraries
kan proberen om ze daar te plaatsen weet niet of dat nodig is. 
gebruik je Arduino IDE 1.6.5 en ESP8266 boardmanager 2.0.0 ?
