### ISSUE TITLE
Na uploaden SPIFFS geen GUI

### ISSUE THREAD

**Issue by ghost** [koffienl/ESPimatic#14]
Fantastisch project. Respect :-) 
maar wie kan mij helpen??
Het flashen is (eindelijk) gelukt, maar als ik de html en js bestanden upload, blijf ik de vereenvoudigde webpagina zien met nu een lijst van bestanden die geüpload zijn. Ik krijg maar niet de GUI te zien. 
Heeft iemand een idee wat er fout gaat?

**Comment by koffienl** [comment]
Na het uploaden moet je nog 1 keer je ESP herstarten ;)

**Comment by ghost** [comment]
Dat is snel :-). Ik heb dit ook nadat ik op de reset knop heb gedrukt of spanningsloos heb gemaakt. 
Dit is wat is zie (zijn de path namen te lang misschien)

For webfiles only!!Multiple files possible

Files on flash:
/C:\Users\rukr01\Desktop\ESPimat & 9.59KB , 9820
/css/C:\Users\rukr01\Desktop\ESP  1.53KB , 1563
/C:\Users\rukr01\Desktop\ESPimat ¦\* 10.66KB , 10918
/C:\Users\rukr01\Desktop\ESPimat @+ 10.81KB , 11072
/C:\Users\rukr01\Desktop\ESPimat æV 21.72KB , 22246
/C:\Users\rukr01\Desktop\ESPimat L- 11.32KB , 11596
/C:\Users\rukr01\Desktop\ESPimat Ó 6.21KB , 6355
/js/C:\Users\rukr01\Desktop\ESPi C 323B , 323
/js/C:\Users\rukr01\Desktop\ESPi þ 510B , 510
/C:\Users\rukr01\Desktop\ESPimat % 9.25KB , 9474

**Comment by koffienl** [comment]
Dat zijn wel heel rare filenames, dat klopt niet.
Hoe groot is je SPIFFS van de ESP ? (in de Arduino IDE -> tools -> Flash Size).
Je kunt je SPIFFS formatteren door de pagina http://ipvanjeESP/format op te vragen. Kijk even in de Serial Monitor mee tot je 'format complete' ziet staan. Daarna kun je opnieuw de files uploaden.

**Comment by ghost** [comment]
Helaas vanallegeprobeerd. De files uploaden direct vanaf c:.. ziet er wel goed uit, maar nog steeds krijg ik de GUI niet. Wat mij wel opvalt is dat steeds opnieuw begin ik dit krijg:
SSID: 
ESPimatic
password: 
espimatic
Connected to ESPimatic
IP address: 192.168.4.1
HTTP server started

maar in mijn netwerk zie ik geen ESPimatic, maar ESP_23CF77. Hier kan ik wel mee verbinden zonder password en kom ik op de pagina om mijn SSID in te vullen en password.  Hierna kom ik gewoon weer op de pagina om de bestanden te uploaden. Ik heb het al diverse malen geprobeerd dmv de 
http://www.pratikpanda.com/completely-format-erase-esp8266-flash-memory/

Wat doe ik fout :-(

**Comment by koffienl** [comment]
Wat voor ESP heb je , en hoe zien je settings onder Arduino voor je ESP eruit ?
Dus via de Arduino IDE op Tools klikken en dan alle settings van "Board ..." , "CPu frequnecy" enzo.

**Comment by ghost** [comment]
Board:
8266 ESP-12E (development board (LoLin))
op de print staat:
new NodeMcu V3

detected info (download tool):
flash vendor:
EFh : WB
flash devID: 4016h
QUAD;32Mbit
crystal: 26 Mhz

arduino 1.6.5 info:
Board: NodeMCU 1.0 (ESP-12E)
(ik heb ook generic ESP8266 geprobeerd)
Baud: 115200
CPU freq: 80 Mhz
Flash size: 4M (1M SPIFFS)
Programmer: USBasp

Heb je hier wat aan? Thanks alvast

**Comment by koffienl** [comment]
Je moet je flash szie aanpassen naar 3M SPIFFS en dan opnieuw de code naar de ESP uploaden. Daarna kun je zeer waarschijnlijk gewoon de files uploaden.

**Comment by ghost** [comment]
Helaas was het weer niet gelukt... Totdat ik de bestanden ging uploaden met Chrome ipv IE(v11).
Nogmaals veel dank voor je (snelle!!!) hulp. Top :-)

**Comment by koffienl** [comment]
Fijn dat het nu werkt ;)
Have fun met ESPimatic.

**Comment by ghost** [comment]
Thanks. Ziet er top. :-)
