### ISSUE TITLE
DHT pimatic no humidity

### ISSUE THREAD

**Issue by CIURI86** [koffienl/ESPimatic#3]
The DHT module is not sending the humidity data to the pimatic. Only the temperature is sent .I have tried  with dht11 and dht22 , on the esp the humidity is shown but it is not sending it . Any sugestion where tot look , it's a lot of code ....thx

**Comment by koffienl** [comment]
Known issue, will be fixed in next release ;)

**Comment by koffienl** [comment]
Fixed in version 0.1.24
