### ISSUE TITLE
Announcement :0.1.25

### ISSUE THREAD

**Issue by koffienl** [koffienl/ESPimatic#5]
So far no bugs found for 0.1.24
I Plan to put some small features 0.1.25 at once. Currently working is ADC. The ADC is read an can be pushed to a Pimatic variable on interval. The ADC value can be seen on the homepage.
Next thing I want to test / put in is simple (RGB) LED.
Any other small features and or remarks about 0.1.24 ?

**Comment by koffienl** [comment]
Polling ADC with LDR connected, sending the value every 1 minute to Pimatic

![](https://raw.githubusercontent.com/koffienl/ESPimatic/master/Screenshots/ESPimatic-ADC-Pimatic.PNG)

**Comment by leader21** [comment]
just a thing that i found a little annoying at first flash was the device name had this ??? characters all over. have no screenshot right now, sorry!
could it be possible to also set the device name when asking for the wifi credentials? so the name will be saved to flash and this issue should not occur anymore, doesn't it?
its no real matter, just some cosmetics.

**Comment by koffienl** [comment]
You are right. It's because it is reading 'something' from EEPROM. Hevn't found out how to distinguish such garbage from real info.
This goed for every new value reading from EEPROM.

**Comment by koffienl** [comment]
0.1.25 is released.
For the next version I hope to add LED, deepsleep and perhaps a solution for garbage from EEPROM

**Comment by WasVerzachter** [comment]
Hi koffienl,
found your LDR graph; nice.
How can I read this value from the ESP-api. I tried several url's.
I'm running ESPimatic 0.1.26. ADC value is shown on main screen (sensors). No security / API key filled in.
Using:  curl 'http://<ip-addtess>/api?action=adc&value=status'
gives: curl: (52) Empty reply from server
However I'd like to receive the LDR value which is shown on the main screen.
Thanks in Advance,
Erik

**Comment by incmve** [comment]
as far as I can see ADC is not part of the API (yet?)

**Comment by koffienl** [comment]
Correct, you can't read current valu with the API. But you can send the value in the ADC config page to a pimatic variable every interval.
